include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    curly_braces_in_flow_control_structures: true

    unnecessary_to_list_in_spreads: true

    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    sort_child_properties_last: true

    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
